name=RSbusMaster
version=1.0.0
author=Aiko Pras
maintainer=Aiko Pras
sentence=RS-Bus Master library for RP2040/RP2350
paragraph=Generates RS-Bus polling cycles and receives feedback messages using PIO hardware.
category=Device Control
url=https://github.com/aikopras/RSbusMaster/
includes=RSbusMaster.h
architectures=rp2040
