// File: rsbus_pio.h
//
// The Arduino IDE can not (yet??) compile PIO assemby code itself.
// Therefore we need an offline tool, to compile that assembly code
// and embed the resulting machine code into our Arduino sketch.
// That online tool can be found on: https://wokwi.com/tools/pioasm
//
// For this specific program, we used the PIO assembly code below
//
// The code below generates a 130 pulse cycle, as generated by a RS-Bus master.

/*

.program RSBUS

; clock runs at 4us
; - osr = 130 Pulse counter
; - x is current value of Pulse counter
; - y is 4us counter (main loop low, input loop)
; - isr = received input
; Generates pulses: High = 92us, Low = 108us
; - High: the MOSFET is open, S approaches 0V
; - Low: the MOSFET is closed, decoders are allowed to respond
; If there is input (4800 baud / 208us), the start bit is skipped and the
; 8 data bits are samples at 30%, 40% and 50% of their bittimes.
; With some decoders the start bit may last considerably less than
; 208us. Therefore we sample at 30, 40 and 50% of the bit time
; Once the last bit is sampled, we wait an extra 8 + 20us, to cope with slow decoders

.wrap_target
main_loop:
    pull                    ; pulls initial value from TX FIFO into osr
    mov x, osr              ; x starts from initial value (=130)
    jmp x-- pulse_high      ; compensate that start value is 1 too high
pulse_high:
    set pins, 1 [22]        ; 92us output high
pulse_low:
    set pins, 0             ; set output low
    set y, 11               ; number of times we check for input
check_input:
    jmp pin, get_input      ; do we have input
    jmp y-- check_input     ; no input, keep trying
    jmp x-- pulse_high      ; if (pulseCounter--) > 0 start next pulse
    irq 0                   ; tell main we are done
    jmp main_loop           ; restart, and wait for input

get_input:
    in x, 8                 ; push pulse counter value (= address) into ISR
    set y, 7                ; 8 bits to go ( 0..7)
    nop [24]                ; wait 100 us
    nop [23]                ; wait 96 us

next_bit:
    nop [14]                ; wait 60us
    in pins, 1              ; sample 1
    nop [3]                 ; wait 16us
    in pins, 1              ; sample 2
    nop [3]                 ; wait 16us
    in pins, 1              ; sample 3
    nop [24]                ; wait 100us
    jmp y-- next_bit        ; next bit

    push                    ; send ISR to RX FIFO
    nop [4]                 ; safety margin of 20us, for slow decoders 
    jmp x-- pulse_high      ; continue pulse train
.wrap

*/

// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// RSBUS //
// ----- //

#define RSBUS_wrap_target 0
#define RSBUS_wrap 25

static const uint16_t RSBUS_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block                      
    0xa027, //  1: mov    x, osr                     
    0x0043, //  2: jmp    x--, 3                     
    0xf601, //  3: set    pins, 1                [22]
    0xe000, //  4: set    pins, 0                    
    0xe04b, //  5: set    y, 11                      
    0x00cb, //  6: jmp    pin, 11                    
    0x0086, //  7: jmp    y--, 6                     
    0x0043, //  8: jmp    x--, 3                     
    0xc000, //  9: irq    nowait 0                   
    0x0000, // 10: jmp    0                          
    0x4028, // 11: in     x, 8                       
    0xe047, // 12: set    y, 7                       
    0xb842, // 13: nop                           [24]
    0xb742, // 14: nop                           [23]
    0xae42, // 15: nop                           [14]
    0x4001, // 16: in     pins, 1                    
    0xa342, // 17: nop                           [3] 
    0x4001, // 18: in     pins, 1                    
    0xa342, // 19: nop                           [3] 
    0x4001, // 20: in     pins, 1                    
    0xb842, // 21: nop                           [24]
    0x008f, // 22: jmp    y--, 15                    
    0x8020, // 23: push   block                      
    0xa442, // 24: nop                           [4] 
    0x0043, // 25: jmp    x--, 3                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program RSBUS_program = {
    .instructions = RSBUS_program_instructions,
    .length = 26,
    .origin = -1,
};

static inline pio_sm_config RSBUS_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + RSBUS_wrap_target, offset + RSBUS_wrap);
    return c;
}
#endif
